### PR TITLE
Fix compiling on macOS

### LINKED ISSUE #2: Compiling `glTF-IBL-Sampler` fails
Platform: macOS, arm

I followed the instructions in the repo, and manually cloned the submodule, however I am now hitting build errors with the C++ project. It is very probable this is a me problem. 🙂 

```
Apple clang version 15.0.0 (clang-1500.0.40.1)
Target: arm64-apple-darwin23.2.0
Thread model: posix
```

Errors:

[message.txt](https://github.com/pcwalton/gltf-ibl-sampler-egui/files/13781623/message.txt)

### PR DESCRIPTION
**Pull request by aevyrie**
Fixes #2 

I included the lock file in a separate commit, to give you the option to discard it. It's generally recommended to track a lock file for binaries, to ensure they actually build for end users.

### CODE REVIEW

**Comment by aevyrie** [comment]
Now that I have this building, I am running into an error, with no help from the log: 
image


If this is using Vulkan, and there is no alternative, that will be an issue because afaik macOS does not support Vulkan. If this is the case, the application should probably fail to compile on macOS with a description why.

**Comment by Rigidity** [comment]
Have you looked into [MoltenVK](https://github.com/KhronosGroup/MoltenVK)?

**Comment by viridia** [comment]
Did you ever get this working? I'm running into similar problems on MacOS.

**Comment by aevyrie** [comment]
I had to use windows because this binary uses Vulkan. You might be able to use MoltenVK as a shim for Metal, but I am unfamiliar.

**Pull request closed without merging**
